eShop/Web/MVC/Models/Requests/Basket/AddBasketRequest.cs
using MVC.ViewModels;

namespace MVC.Models.Requests.Basket
{
    public class AddBasketRequest
    {
        public CatalogItem Item { get; set; }
    }
}

eShop/Web/MVC/Models/Requests/Basket/DeleteBasketRequest.cs
using MVC.ViewModels;

namespace MVC.Models.Requests.Basket
{
    public class DeleteBasketRequest
    {
        public CatalogItem Item { get; set; }
    }
}

eShop/Web/MVC/Models/Requests/Basket/GetBasketRequest.cs
namespace MVC.Models.Requests.Basket
{
    public class GetBasketRequest
    {
        public int Id { get; set; }
    }
}

eShop/Web/MVC/ViewModels/Basket.cs
namespace MVC.ViewModels
{
    public record Basket
    {
        public List<CatalogItem> Data { get; set; }
        public string UserId { get; set; }
    }
}

eShop/Web/MVC/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Services.Interfaces;

namespace MVC.Controllers
{
    public class BasketController : Controller
    {
        private IBasketService _basketService;
        private readonly ICatalogService _catalogService;

        public BasketController(IBasketService basketService, ICatalogService catalogService)
        {
            _basketService = basketService;
            _catalogService = catalogService;
        }
        public async Task<IActionResult> Add(int catalogItemId)
        {
            var catalogItem = await _catalogService.GetItemId(catalogItemId);
            await _basketService.AddBasket(catalogItem);

            return Redirect("~/");
        }

        public async Task<IActionResult> Delete(int catalogItemId)
        {
            var catalogItem = await _catalogService.GetItemId(catalogItemId);
            await _basketService.DeleteBasket(catalogItem);
            

            return Redirect("~/Basket/Get");
        }

        public async Task<IActionResult> Get()
        {
            var model = await _basketService.GetBasket();

            return View(model);
        }


    }
}

eShop/Web/MVC/Controllers/CatalogController.cs
using MVC.Services.Interfaces;
using MVC.ViewModels.CatalogViewModels;
using MVC.ViewModels.Pagination;

namespace MVC.Controllers;

public class CatalogController : Controller
{
    private  readonly ICatalogService _catalogService;

    public CatalogController(ICatalogService catalogService)
    {
        _catalogService = catalogService;
    }

    public async Task<IActionResult> Index(int? categoryFilterApplied, int? page, int? itemsPage)
    {   
        page ??= 0;
        itemsPage ??= 6;
        
        var catalog = await _catalogService.GetCatalogItems(page.Value, itemsPage.Value, categoryFilterApplied);
        if (catalog == null)
        {
            return View("Error");
        }
        var info = new PaginationInfo()
        {
            ActualPage = page.Value,
            ItemsPerPage = catalog.Data.Count,
            TotalItems = catalog.Count,
            TotalPages = (int)Math.Ceiling((decimal)catalog.Count / itemsPage.Value)
        };
        var vm = new IndexViewModel()
        {
            CatalogItems = catalog.Data,
            Categories = await _catalogService.GetCategories(),
            PaginationInfo = info
        };

        vm.PaginationInfo.Next = (vm.PaginationInfo.ActualPage == vm.PaginationInfo.TotalPages - 1) ? "is-disabled" : "";
        vm.PaginationInfo.Previous = (vm.PaginationInfo.ActualPage == 0) ? "is-disabled" : "";

        return View(vm);
    }
}

eShop/Web/MVC/Views/Basket/Get.cshtml
@model MVC.ViewModels.Basket

<h2>Basket</h2>

@if (Model.Data.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Data)
            {
                <tr>
                    <td>@item.Title</td>
                    <td>@item.Price</td>
                    <td>
                        <form asp-controller="Basket" asp-action="Delete" method="post">
                            <input type="hidden" name="catalogItemId" value="@item.Id" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div>Your basket is empty</div>
}

<div>
    <a asp-controller="Catalog" asp-action="Index">Back to catalog</a>
</div>